version: 2.1

orbs:
  node: "circleci/node@5.1.0"

jobs:
  test:
    executor:
      name: "node/default"
      tag: "18.15.0"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: "Run all tests"
          command: yarn run test


workflows:
  test:
    jobs:
      - test
